//
//  PCConnect4.h
//  Connect4
//
//  Created by Richard Lichkus on 8/1/14.
//  Copyright (c) 2014 CleverKnot LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PCConnect4 : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* connect4BoardTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bluePieceTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* redPieceTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* circleTableTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* slotTableTargets;

// Drawing Methods
+ (void)drawConnect4Board;
+ (void)drawBluePiece;
+ (void)drawRedPiece;
+ (void)drawCircleTableWithScaleCircle: (CGFloat)scaleCircle;
+ (void)drawSlotTableWithNumber2: (CGFloat)number2 dx: (CGFloat)dx;

// Generated Images
+ (UIImage*)imageOfConnect4Board;
+ (UIImage*)imageOfBluePiece;
+ (UIImage*)imageOfRedPiece;
+ (UIImage*)imageOfCircleTableWithScaleCircle: (CGFloat)scaleCircle;
+ (UIImage*)imageOfSlotTableWithNumber2: (CGFloat)number2 dx: (CGFloat)dx;

@end
