//
//  PCConnect4.m
//  Connect4
//
//  Created by Richard Lichkus on 8/1/14.
//  Copyright (c) 2014 CleverKnot LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PCConnect4.h"


@implementation PCConnect4

#pragma mark Cache

static UIImage* _imageOfConnect4Board = nil;
static UIImage* _imageOfBluePiece = nil;
static UIImage* _imageOfRedPiece = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawConnect4Board;
{
    //// Color Declarations
    UIColor* gameBoardYellow = [UIColor colorWithRed: 0.991 green: 0.982 blue: 0.069 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(477.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 67.27) controlPoint1: CGPointMake(465.42, 35.03) controlPoint2: CGPointMake(465.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 67.27) controlPoint1: CGPointMake(490.03, 79.58) controlPoint2: CGPointMake(509.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 22.73) controlPoint1: CGPointMake(534.58, 54.97) controlPoint2: CGPointMake(534.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 22.73) controlPoint1: CGPointMake(509.97, 10.42) controlPoint2: CGPointMake(490.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 67.27) controlPoint1: CGPointMake(395.42, 35.03) controlPoint2: CGPointMake(395.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 67.27) controlPoint1: CGPointMake(420.03, 79.58) controlPoint2: CGPointMake(439.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 22.73) controlPoint1: CGPointMake(464.58, 54.97) controlPoint2: CGPointMake(464.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 22.73) controlPoint1: CGPointMake(439.97, 10.42) controlPoint2: CGPointMake(420.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 67.27) controlPoint1: CGPointMake(325.42, 35.03) controlPoint2: CGPointMake(325.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 67.27) controlPoint1: CGPointMake(350.03, 79.58) controlPoint2: CGPointMake(369.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 22.73) controlPoint1: CGPointMake(394.58, 54.97) controlPoint2: CGPointMake(394.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 22.73) controlPoint1: CGPointMake(369.97, 10.42) controlPoint2: CGPointMake(350.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 67.27) controlPoint1: CGPointMake(255.42, 35.03) controlPoint2: CGPointMake(255.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 67.27) controlPoint1: CGPointMake(280.03, 79.58) controlPoint2: CGPointMake(299.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 22.73) controlPoint1: CGPointMake(324.58, 54.97) controlPoint2: CGPointMake(324.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 22.73) controlPoint1: CGPointMake(299.97, 10.42) controlPoint2: CGPointMake(280.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 67.27) controlPoint1: CGPointMake(185.42, 35.03) controlPoint2: CGPointMake(185.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 67.27) controlPoint1: CGPointMake(210.03, 79.58) controlPoint2: CGPointMake(229.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 22.73) controlPoint1: CGPointMake(254.58, 54.97) controlPoint2: CGPointMake(254.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 22.73) controlPoint1: CGPointMake(229.97, 10.42) controlPoint2: CGPointMake(210.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 67.27) controlPoint1: CGPointMake(115.42, 35.03) controlPoint2: CGPointMake(115.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 67.27) controlPoint1: CGPointMake(140.03, 79.58) controlPoint2: CGPointMake(159.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 22.73) controlPoint1: CGPointMake(184.58, 54.97) controlPoint2: CGPointMake(184.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 22.73) controlPoint1: CGPointMake(159.97, 10.42) controlPoint2: CGPointMake(140.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 67.27) controlPoint1: CGPointMake(45.42, 35.03) controlPoint2: CGPointMake(45.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 67.27) controlPoint1: CGPointMake(70.03, 79.58) controlPoint2: CGPointMake(89.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 22.73) controlPoint1: CGPointMake(114.58, 54.97) controlPoint2: CGPointMake(114.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 22.73) controlPoint1: CGPointMake(89.97, 10.42) controlPoint2: CGPointMake(70.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 137.27) controlPoint1: CGPointMake(465.42, 105.03) controlPoint2: CGPointMake(465.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 137.27) controlPoint1: CGPointMake(490.03, 149.58) controlPoint2: CGPointMake(509.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 92.73) controlPoint1: CGPointMake(534.58, 124.97) controlPoint2: CGPointMake(534.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 92.73) controlPoint1: CGPointMake(509.97, 80.42) controlPoint2: CGPointMake(490.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 137.27) controlPoint1: CGPointMake(395.42, 105.03) controlPoint2: CGPointMake(395.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 137.27) controlPoint1: CGPointMake(420.03, 149.58) controlPoint2: CGPointMake(439.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 92.73) controlPoint1: CGPointMake(464.58, 124.97) controlPoint2: CGPointMake(464.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 92.73) controlPoint1: CGPointMake(439.97, 80.42) controlPoint2: CGPointMake(420.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 137.27) controlPoint1: CGPointMake(325.42, 105.03) controlPoint2: CGPointMake(325.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 137.27) controlPoint1: CGPointMake(350.03, 149.58) controlPoint2: CGPointMake(369.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 92.73) controlPoint1: CGPointMake(394.58, 124.97) controlPoint2: CGPointMake(394.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 92.73) controlPoint1: CGPointMake(369.97, 80.42) controlPoint2: CGPointMake(350.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 137.27) controlPoint1: CGPointMake(255.42, 105.03) controlPoint2: CGPointMake(255.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 137.27) controlPoint1: CGPointMake(280.03, 149.58) controlPoint2: CGPointMake(299.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 92.73) controlPoint1: CGPointMake(324.58, 124.97) controlPoint2: CGPointMake(324.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 92.73) controlPoint1: CGPointMake(299.97, 80.42) controlPoint2: CGPointMake(280.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 137.27) controlPoint1: CGPointMake(185.42, 105.03) controlPoint2: CGPointMake(185.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 137.27) controlPoint1: CGPointMake(210.03, 149.58) controlPoint2: CGPointMake(229.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 92.73) controlPoint1: CGPointMake(254.58, 124.97) controlPoint2: CGPointMake(254.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 92.73) controlPoint1: CGPointMake(229.97, 80.42) controlPoint2: CGPointMake(210.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 137.27) controlPoint1: CGPointMake(115.42, 105.03) controlPoint2: CGPointMake(115.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 137.27) controlPoint1: CGPointMake(140.03, 149.58) controlPoint2: CGPointMake(159.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 92.73) controlPoint1: CGPointMake(184.58, 124.97) controlPoint2: CGPointMake(184.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 92.73) controlPoint1: CGPointMake(159.97, 80.42) controlPoint2: CGPointMake(140.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 137.27) controlPoint1: CGPointMake(45.42, 105.03) controlPoint2: CGPointMake(45.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 137.27) controlPoint1: CGPointMake(70.03, 149.58) controlPoint2: CGPointMake(89.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 92.73) controlPoint1: CGPointMake(114.58, 124.97) controlPoint2: CGPointMake(114.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 92.73) controlPoint1: CGPointMake(89.97, 80.42) controlPoint2: CGPointMake(70.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 207.27) controlPoint1: CGPointMake(465.42, 175.03) controlPoint2: CGPointMake(465.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 207.27) controlPoint1: CGPointMake(490.03, 219.58) controlPoint2: CGPointMake(509.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 162.73) controlPoint1: CGPointMake(534.58, 194.97) controlPoint2: CGPointMake(534.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 162.73) controlPoint1: CGPointMake(509.97, 150.42) controlPoint2: CGPointMake(490.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 207.27) controlPoint1: CGPointMake(395.42, 175.03) controlPoint2: CGPointMake(395.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 207.27) controlPoint1: CGPointMake(420.03, 219.58) controlPoint2: CGPointMake(439.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 162.73) controlPoint1: CGPointMake(464.58, 194.97) controlPoint2: CGPointMake(464.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 162.73) controlPoint1: CGPointMake(439.97, 150.42) controlPoint2: CGPointMake(420.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 207.27) controlPoint1: CGPointMake(325.42, 175.03) controlPoint2: CGPointMake(325.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 207.27) controlPoint1: CGPointMake(350.03, 219.58) controlPoint2: CGPointMake(369.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 162.73) controlPoint1: CGPointMake(394.58, 194.97) controlPoint2: CGPointMake(394.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 162.73) controlPoint1: CGPointMake(369.97, 150.42) controlPoint2: CGPointMake(350.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 207.27) controlPoint1: CGPointMake(255.42, 175.03) controlPoint2: CGPointMake(255.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 207.27) controlPoint1: CGPointMake(280.03, 219.58) controlPoint2: CGPointMake(299.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 162.73) controlPoint1: CGPointMake(324.58, 194.97) controlPoint2: CGPointMake(324.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 162.73) controlPoint1: CGPointMake(299.97, 150.42) controlPoint2: CGPointMake(280.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 207.27) controlPoint1: CGPointMake(185.42, 175.03) controlPoint2: CGPointMake(185.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 207.27) controlPoint1: CGPointMake(210.03, 219.58) controlPoint2: CGPointMake(229.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 162.73) controlPoint1: CGPointMake(254.58, 194.97) controlPoint2: CGPointMake(254.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 162.73) controlPoint1: CGPointMake(229.97, 150.42) controlPoint2: CGPointMake(210.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 207.27) controlPoint1: CGPointMake(115.42, 175.03) controlPoint2: CGPointMake(115.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 207.27) controlPoint1: CGPointMake(140.03, 219.58) controlPoint2: CGPointMake(159.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 162.73) controlPoint1: CGPointMake(184.58, 194.97) controlPoint2: CGPointMake(184.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 162.73) controlPoint1: CGPointMake(159.97, 150.42) controlPoint2: CGPointMake(140.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 207.27) controlPoint1: CGPointMake(45.42, 175.03) controlPoint2: CGPointMake(45.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 207.27) controlPoint1: CGPointMake(70.03, 219.58) controlPoint2: CGPointMake(89.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 162.73) controlPoint1: CGPointMake(114.58, 194.97) controlPoint2: CGPointMake(114.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 162.73) controlPoint1: CGPointMake(89.97, 150.42) controlPoint2: CGPointMake(70.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(128.23, 232.23)];
    [bezierPath addCurveToPoint: CGPointMake(128.23, 276.77) controlPoint1: CGPointMake(115.92, 244.53) controlPoint2: CGPointMake(115.92, 264.47)];
    [bezierPath addCurveToPoint: CGPointMake(172.77, 276.77) controlPoint1: CGPointMake(140.53, 289.08) controlPoint2: CGPointMake(160.47, 289.08)];
    [bezierPath addCurveToPoint: CGPointMake(172.77, 232.23) controlPoint1: CGPointMake(185.08, 264.47) controlPoint2: CGPointMake(185.08, 244.53)];
    [bezierPath addCurveToPoint: CGPointMake(128.23, 232.23) controlPoint1: CGPointMake(160.47, 219.92) controlPoint2: CGPointMake(140.53, 219.92)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 277.27) controlPoint1: CGPointMake(465.42, 245.03) controlPoint2: CGPointMake(465.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 277.27) controlPoint1: CGPointMake(490.03, 289.58) controlPoint2: CGPointMake(509.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 232.73) controlPoint1: CGPointMake(534.58, 264.97) controlPoint2: CGPointMake(534.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 232.73) controlPoint1: CGPointMake(509.97, 220.42) controlPoint2: CGPointMake(490.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 277.27) controlPoint1: CGPointMake(395.42, 245.03) controlPoint2: CGPointMake(395.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 277.27) controlPoint1: CGPointMake(420.03, 289.58) controlPoint2: CGPointMake(439.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 232.73) controlPoint1: CGPointMake(464.58, 264.97) controlPoint2: CGPointMake(464.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 232.73) controlPoint1: CGPointMake(439.97, 220.42) controlPoint2: CGPointMake(420.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 277.27) controlPoint1: CGPointMake(325.42, 245.03) controlPoint2: CGPointMake(325.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 277.27) controlPoint1: CGPointMake(350.03, 289.58) controlPoint2: CGPointMake(369.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 232.73) controlPoint1: CGPointMake(394.58, 264.97) controlPoint2: CGPointMake(394.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 232.73) controlPoint1: CGPointMake(369.97, 220.42) controlPoint2: CGPointMake(350.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 277.27) controlPoint1: CGPointMake(255.42, 245.03) controlPoint2: CGPointMake(255.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 277.27) controlPoint1: CGPointMake(280.03, 289.58) controlPoint2: CGPointMake(299.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 232.73) controlPoint1: CGPointMake(324.58, 264.97) controlPoint2: CGPointMake(324.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 232.73) controlPoint1: CGPointMake(299.97, 220.42) controlPoint2: CGPointMake(280.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 277.27) controlPoint1: CGPointMake(185.42, 245.03) controlPoint2: CGPointMake(185.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 277.27) controlPoint1: CGPointMake(210.03, 289.58) controlPoint2: CGPointMake(229.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 232.73) controlPoint1: CGPointMake(254.58, 264.97) controlPoint2: CGPointMake(254.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 232.73) controlPoint1: CGPointMake(229.97, 220.42) controlPoint2: CGPointMake(210.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 277.27) controlPoint1: CGPointMake(45.42, 245.03) controlPoint2: CGPointMake(45.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 277.27) controlPoint1: CGPointMake(70.03, 289.58) controlPoint2: CGPointMake(89.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 232.73) controlPoint1: CGPointMake(114.58, 264.97) controlPoint2: CGPointMake(114.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 232.73) controlPoint1: CGPointMake(89.97, 220.42) controlPoint2: CGPointMake(70.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 347.27) controlPoint1: CGPointMake(465.42, 315.03) controlPoint2: CGPointMake(465.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 347.27) controlPoint1: CGPointMake(490.03, 359.58) controlPoint2: CGPointMake(509.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 302.73) controlPoint1: CGPointMake(534.58, 334.97) controlPoint2: CGPointMake(534.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 302.73) controlPoint1: CGPointMake(509.97, 290.42) controlPoint2: CGPointMake(490.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 347.27) controlPoint1: CGPointMake(395.42, 315.03) controlPoint2: CGPointMake(395.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 347.27) controlPoint1: CGPointMake(420.03, 359.58) controlPoint2: CGPointMake(439.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 302.73) controlPoint1: CGPointMake(464.58, 334.97) controlPoint2: CGPointMake(464.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 302.73) controlPoint1: CGPointMake(439.97, 290.42) controlPoint2: CGPointMake(420.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 347.27) controlPoint1: CGPointMake(325.42, 315.03) controlPoint2: CGPointMake(325.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 347.27) controlPoint1: CGPointMake(350.03, 359.58) controlPoint2: CGPointMake(369.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 302.73) controlPoint1: CGPointMake(394.58, 334.97) controlPoint2: CGPointMake(394.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 302.73) controlPoint1: CGPointMake(369.97, 290.42) controlPoint2: CGPointMake(350.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 347.27) controlPoint1: CGPointMake(255.42, 315.03) controlPoint2: CGPointMake(255.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 347.27) controlPoint1: CGPointMake(280.03, 359.58) controlPoint2: CGPointMake(299.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 302.73) controlPoint1: CGPointMake(324.58, 334.97) controlPoint2: CGPointMake(324.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 302.73) controlPoint1: CGPointMake(299.97, 290.42) controlPoint2: CGPointMake(280.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 347.27) controlPoint1: CGPointMake(185.42, 315.03) controlPoint2: CGPointMake(185.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 347.27) controlPoint1: CGPointMake(210.03, 359.58) controlPoint2: CGPointMake(229.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 302.73) controlPoint1: CGPointMake(254.58, 334.97) controlPoint2: CGPointMake(254.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 302.73) controlPoint1: CGPointMake(229.97, 290.42) controlPoint2: CGPointMake(210.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 347.27) controlPoint1: CGPointMake(115.42, 315.03) controlPoint2: CGPointMake(115.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 347.27) controlPoint1: CGPointMake(140.03, 359.58) controlPoint2: CGPointMake(159.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 302.73) controlPoint1: CGPointMake(184.58, 334.97) controlPoint2: CGPointMake(184.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 302.73) controlPoint1: CGPointMake(159.97, 290.42) controlPoint2: CGPointMake(140.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 347.27) controlPoint1: CGPointMake(45.42, 315.03) controlPoint2: CGPointMake(45.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 347.27) controlPoint1: CGPointMake(70.03, 359.58) controlPoint2: CGPointMake(89.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 302.73) controlPoint1: CGPointMake(114.58, 334.97) controlPoint2: CGPointMake(114.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 302.73) controlPoint1: CGPointMake(89.97, 290.42) controlPoint2: CGPointMake(70.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 417.27) controlPoint1: CGPointMake(465.42, 385.03) controlPoint2: CGPointMake(465.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 417.27) controlPoint1: CGPointMake(490.03, 429.58) controlPoint2: CGPointMake(509.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 372.73) controlPoint1: CGPointMake(534.58, 404.97) controlPoint2: CGPointMake(534.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 372.73) controlPoint1: CGPointMake(509.97, 360.42) controlPoint2: CGPointMake(490.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 417.27) controlPoint1: CGPointMake(395.42, 385.03) controlPoint2: CGPointMake(395.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 417.27) controlPoint1: CGPointMake(420.03, 429.58) controlPoint2: CGPointMake(439.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 372.73) controlPoint1: CGPointMake(464.58, 404.97) controlPoint2: CGPointMake(464.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 372.73) controlPoint1: CGPointMake(439.97, 360.42) controlPoint2: CGPointMake(420.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 417.27) controlPoint1: CGPointMake(325.42, 385.03) controlPoint2: CGPointMake(325.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 417.27) controlPoint1: CGPointMake(350.03, 429.58) controlPoint2: CGPointMake(369.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 372.73) controlPoint1: CGPointMake(394.58, 404.97) controlPoint2: CGPointMake(394.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 372.73) controlPoint1: CGPointMake(369.97, 360.42) controlPoint2: CGPointMake(350.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 417.27) controlPoint1: CGPointMake(255.42, 385.03) controlPoint2: CGPointMake(255.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 417.27) controlPoint1: CGPointMake(280.03, 429.58) controlPoint2: CGPointMake(299.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 372.73) controlPoint1: CGPointMake(324.58, 404.97) controlPoint2: CGPointMake(324.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 372.73) controlPoint1: CGPointMake(299.97, 360.42) controlPoint2: CGPointMake(280.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 417.27) controlPoint1: CGPointMake(185.42, 385.03) controlPoint2: CGPointMake(185.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 417.27) controlPoint1: CGPointMake(210.03, 429.58) controlPoint2: CGPointMake(229.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 372.73) controlPoint1: CGPointMake(254.58, 404.97) controlPoint2: CGPointMake(254.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 372.73) controlPoint1: CGPointMake(229.97, 360.42) controlPoint2: CGPointMake(210.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 417.27) controlPoint1: CGPointMake(115.42, 385.03) controlPoint2: CGPointMake(115.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 417.27) controlPoint1: CGPointMake(140.03, 429.58) controlPoint2: CGPointMake(159.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 372.73) controlPoint1: CGPointMake(184.58, 404.97) controlPoint2: CGPointMake(184.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 372.73) controlPoint1: CGPointMake(159.97, 360.42) controlPoint2: CGPointMake(140.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 417.27) controlPoint1: CGPointMake(45.42, 385.03) controlPoint2: CGPointMake(45.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 417.27) controlPoint1: CGPointMake(70.03, 429.58) controlPoint2: CGPointMake(89.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 372.73) controlPoint1: CGPointMake(114.58, 404.97) controlPoint2: CGPointMake(114.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 372.73) controlPoint1: CGPointMake(89.97, 360.42) controlPoint2: CGPointMake(70.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(545, 0)];
    [bezierPath addCurveToPoint: CGPointMake(545, 440) controlPoint1: CGPointMake(545, 0) controlPoint2: CGPointMake(545, 440)];
    [bezierPath addLineToPoint: CGPointMake(35, 440)];
    [bezierPath addLineToPoint: CGPointMake(35, 0)];
    [bezierPath addLineToPoint: CGPointMake(545, 0)];
    [bezierPath addLineToPoint: CGPointMake(545, 0)];
    [bezierPath closePath];
    [gameBoardYellow setFill];
    [bezierPath fill];


    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(545, 0, 20, 507)];
    [gameBoardYellow setFill];
    [rectanglePath fill];


    //// Rectangle 3 Drawing
    UIBezierPath* rectangle3Path = [UIBezierPath bezierPathWithRect: CGRectMake(15, 0, 20, 507)];
    [gameBoardYellow setFill];
    [rectangle3Path fill];


    //// Rectangle 4 Drawing
    UIBezierPath* rectangle4Path = [UIBezierPath bezierPathWithRect: CGRectMake(530, 487, 50, 20)];
    [gameBoardYellow setFill];
    [rectangle4Path fill];


    //// Rectangle 5 Drawing
    UIBezierPath* rectangle5Path = [UIBezierPath bezierPathWithRect: CGRectMake(0, 487, 50, 20)];
    [gameBoardYellow setFill];
    [rectangle5Path fill];
}

+ (void)drawBluePiece;
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* pieceBlue = [UIColor colorWithRed: 0.135 green: 0.566 blue: 0.854 alpha: 1];
    CGFloat pieceBlueRGBA[4];
    [pieceBlue getRed: &pieceBlueRGBA[0] green: &pieceBlueRGBA[1] blue: &pieceBlueRGBA[2] alpha: &pieceBlueRGBA[3]];

    UIColor* shadowPieceBlue = [UIColor colorWithRed: (pieceBlueRGBA[0] * 0.7) green: (pieceBlueRGBA[1] * 0.7) blue: (pieceBlueRGBA[2] * 0.7) alpha: (pieceBlueRGBA[3] * 0.7 + 0.3)];

    //// Gradient Declarations
    CGFloat blueGamePieceLocations[] = {0, 0.41, 1};
    CGGradientRef blueGamePiece = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)pieceBlue.CGColor, (id)[UIColor colorWithRed: 0.115 green: 0.481 blue: 0.726 alpha: 1].CGColor, (id)shadowPieceBlue.CGColor], blueGamePieceLocations);

    //// Oval Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 35, 35);

    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-35, -35, 70, 70)];
    [shadowPieceBlue setFill];
    [ovalPath fill];

    CGContextRestoreGState(context);


    //// Oval 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 35, 35);

    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-32.5, -32.5, 65, 65)];
    CGContextSaveGState(context);
    [oval2Path addClip];
    CGContextDrawRadialGradient(context, blueGamePiece,
        CGPointMake(-1.59, -2.7), 34.14,
        CGPointMake(0, 0), 23.94,
        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
    CGContextRestoreGState(context);

    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(blueGamePiece);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawRedPiece;
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* pieceRed = [UIColor colorWithRed: 0.968 green: 0.272 blue: 0.108 alpha: 1];
    CGFloat pieceRedRGBA[4];
    [pieceRed getRed: &pieceRedRGBA[0] green: &pieceRedRGBA[1] blue: &pieceRedRGBA[2] alpha: &pieceRedRGBA[3]];

    UIColor* shadowPieceRed = [UIColor colorWithRed: (pieceRedRGBA[0] * 0.8) green: (pieceRedRGBA[1] * 0.8) blue: (pieceRedRGBA[2] * 0.8) alpha: (pieceRedRGBA[3] * 0.8 + 0.2)];

    //// Gradient Declarations
    CGFloat redGamePieceLocations[] = {0, 1};
    CGGradientRef redGamePiece = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)pieceRed.CGColor, (id)shadowPieceRed.CGColor], redGamePieceLocations);

    //// Oval Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 35, 35);

    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-35, -35, 70, 70)];
    [shadowPieceRed setFill];
    [ovalPath fill];

    CGContextRestoreGState(context);


    //// Oval 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 35, 35);

    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-32.5, -32.5, 65, 65)];
    CGContextSaveGState(context);
    [oval2Path addClip];
    CGContextDrawRadialGradient(context, redGamePiece,
        CGPointMake(-1.59, -2.7), 34.14,
        CGPointMake(0, 0), 23.94,
        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
    CGContextRestoreGState(context);

    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(redGamePiece);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawCircleTableWithScaleCircle: (CGFloat)scaleCircle;
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    CGFloat scaleX = scaleCircle;
    CGFloat scaleY = scaleCircle;

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 212, 640, 73)];
    [UIColor.lightGrayColor setFill];
    [rectanglePath fill];


    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(163.73, 63.43)];
    [bezierPath addCurveToPoint: CGPointMake(163.73, 147.57) controlPoint1: CGPointMake(77.42, 86.66) controlPoint2: CGPointMake(77.42, 124.34)];
    [bezierPath addCurveToPoint: CGPointMake(476.27, 147.57) controlPoint1: CGPointMake(250.04, 170.81) controlPoint2: CGPointMake(389.96, 170.81)];
    [bezierPath addCurveToPoint: CGPointMake(476.27, 63.43) controlPoint1: CGPointMake(562.58, 124.34) controlPoint2: CGPointMake(562.58, 86.66)];
    [bezierPath addCurveToPoint: CGPointMake(163.73, 63.43) controlPoint1: CGPointMake(389.96, 40.19) controlPoint2: CGPointMake(250.04, 40.19)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(550, 0)];
    [bezierPath addCurveToPoint: CGPointMake(640, 212) controlPoint1: CGPointMake(550, 0) controlPoint2: CGPointMake(640, 212)];
    [bezierPath addLineToPoint: CGPointMake(0, 212)];
    [bezierPath addLineToPoint: CGPointMake(90, 0)];
    [bezierPath addLineToPoint: CGPointMake(550, 0)];
    [bezierPath addLineToPoint: CGPointMake(550, 0)];
    [bezierPath closePath];
    [UIColor.grayColor setFill];
    [bezierPath fill];


    //// Bezier 3 Drawing
    UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
    [bezier3Path moveToPoint: CGPointMake(163.73, 58.43)];
    [bezier3Path addCurveToPoint: CGPointMake(116.9, 124) controlPoint1: CGPointMake(97.88, 76.16) controlPoint2: CGPointMake(82.27, 102.29)];
    [bezier3Path addCurveToPoint: CGPointMake(163.73, 105.43) controlPoint1: CGPointMake(127.66, 117.25) controlPoint2: CGPointMake(143.27, 110.93)];
    [bezier3Path addCurveToPoint: CGPointMake(476.27, 105.43) controlPoint1: CGPointMake(250.04, 82.19) controlPoint2: CGPointMake(389.96, 82.19)];
    [bezier3Path addCurveToPoint: CGPointMake(523.1, 124) controlPoint1: CGPointMake(496.73, 110.93) controlPoint2: CGPointMake(512.34, 117.25)];
    [bezier3Path addCurveToPoint: CGPointMake(476.27, 58.43) controlPoint1: CGPointMake(557.73, 102.29) controlPoint2: CGPointMake(542.12, 76.16)];
    [bezier3Path addCurveToPoint: CGPointMake(163.73, 58.43) controlPoint1: CGPointMake(389.96, 35.19) controlPoint2: CGPointMake(250.04, 35.19)];
    [bezier3Path closePath];
    [UIColor.lightGrayColor setFill];
    [bezier3Path fill];


    //// Oval Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 320, 105.5);
    CGContextScaleCTM(context, scaleX, scaleY);

    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-227, -65.5, 454, 131)];
    [UIColor.grayColor setFill];
    [ovalPath fill];

    CGContextRestoreGState(context);
}

+ (void)drawSlotTableWithNumber2: (CGFloat)number2 dx: (CGFloat)dx;
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    CGFloat number = 32;
    CGFloat expression = number - dx;
    CGFloat expression2 = number2 + dx;

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 212, 640, 73)];
    [UIColor.lightGrayColor setFill];
    [rectanglePath fill];


    //// Rectangle 3 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, expression, 136);

    UIBezierPath* rectangle3Path = UIBezierPath.bezierPath;
    [rectangle3Path moveToPoint: CGPointMake(0, 34)];
    [rectangle3Path addLineToPoint: CGPointMake(288, 34)];
    [rectangle3Path addLineToPoint: CGPointMake(288, 0)];
    [rectangle3Path addLineToPoint: CGPointMake(0, 0)];
    [rectangle3Path addLineToPoint: CGPointMake(0, 34)];
    [rectangle3Path closePath];
    [UIColor.lightGrayColor setFill];
    [rectangle3Path fill];

    CGContextRestoreGState(context);


    //// Rectangle 4 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, expression2, 136);

    UIBezierPath* rectangle4Path = UIBezierPath.bezierPath;
    [rectangle4Path moveToPoint: CGPointMake(0, 34)];
    [rectangle4Path addLineToPoint: CGPointMake(287, 34)];
    [rectangle4Path addLineToPoint: CGPointMake(287, 0)];
    [rectangle4Path addLineToPoint: CGPointMake(0, 0)];
    [rectangle4Path addLineToPoint: CGPointMake(0, 34)];
    [rectangle4Path closePath];
    [UIColor.lightGrayColor setFill];
    [rectangle4Path fill];

    CGContextRestoreGState(context);


    //// Bezier 6 Drawing
    UIBezierPath* bezier6Path = UIBezierPath.bezierPath;
    [bezier6Path moveToPoint: CGPointMake(550, 0)];
    [bezier6Path addCurveToPoint: CGPointMake(595, 106) controlPoint1: CGPointMake(550, 0) controlPoint2: CGPointMake(572.5, 53)];
    [bezier6Path addCurveToPoint: CGPointMake(582, 76) controlPoint1: CGPointMake(588.5, 91) controlPoint2: CGPointMake(582, 76)];
    [bezier6Path addLineToPoint: CGPointMake(57.74, 76)];
    [bezier6Path addCurveToPoint: CGPointMake(90, 0) controlPoint1: CGPointMake(75.27, 34.69) controlPoint2: CGPointMake(90, 0)];
    [bezier6Path addLineToPoint: CGPointMake(550, 0)];
    [bezier6Path addLineToPoint: CGPointMake(550, 0)];
    [bezier6Path closePath];
    [bezier6Path moveToPoint: CGPointMake(607.74, 136)];
    [bezier6Path addCurveToPoint: CGPointMake(640, 212) controlPoint1: CGPointMake(625.27, 177.31) controlPoint2: CGPointMake(640, 212)];
    [bezier6Path addLineToPoint: CGPointMake(0, 212)];
    [bezier6Path addCurveToPoint: CGPointMake(32.26, 136) controlPoint1: CGPointMake(0, 212) controlPoint2: CGPointMake(14.73, 177.31)];
    [bezier6Path addLineToPoint: CGPointMake(320, 136)];
    [bezier6Path addLineToPoint: CGPointMake(607.74, 136)];
    [bezier6Path closePath];
    [UIColor.grayColor setFill];
    [bezier6Path fill];


    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = UIBezierPath.bezierPath;
    [rectangle2Path moveToPoint: CGPointMake(58, 110)];
    [rectangle2Path addLineToPoint: CGPointMake(582, 110)];
    [rectangle2Path addLineToPoint: CGPointMake(582, 76)];
    [rectangle2Path addLineToPoint: CGPointMake(58, 76)];
    [rectangle2Path addLineToPoint: CGPointMake(58, 110)];
    [rectangle2Path closePath];
    [UIColor.lightGrayColor setFill];
    [rectangle2Path fill];


    //// Bezier 4 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, expression, 76);

    UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
    [bezier4Path moveToPoint: CGPointMake(0, 60)];
    [bezier4Path addLineToPoint: CGPointMake(288, 60)];
    [bezier4Path addLineToPoint: CGPointMake(288, 0)];
    [bezier4Path addLineToPoint: CGPointMake(26, 0)];
    [bezier4Path addLineToPoint: CGPointMake(0, 60)];
    [bezier4Path closePath];
    [UIColor.grayColor setFill];
    [bezier4Path fill];

    CGContextRestoreGState(context);


    //// Bezier 5 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, expression2, 76);

    UIBezierPath* bezier5Path = UIBezierPath.bezierPath;
    [bezier5Path moveToPoint: CGPointMake(0, 60)];
    [bezier5Path addLineToPoint: CGPointMake(287.5, 60)];
    [bezier5Path addLineToPoint: CGPointMake(262, 0)];
    [bezier5Path addLineToPoint: CGPointMake(0, 0)];
    [bezier5Path addLineToPoint: CGPointMake(0, 0)];
    [bezier5Path addLineToPoint: CGPointMake(0, 60)];
    [bezier5Path closePath];
    [UIColor.grayColor setFill];
    [bezier5Path fill];

    CGContextRestoreGState(context);
}

#pragma mark Generated Images

+ (UIImage*)imageOfConnect4Board;
{
    if (_imageOfConnect4Board)
        return _imageOfConnect4Board;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(580, 508), NO, 0.0f);
    [PCConnect4 drawConnect4Board];
    _imageOfConnect4Board = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfConnect4Board;
}

+ (UIImage*)imageOfBluePiece;
{
    if (_imageOfBluePiece)
        return _imageOfBluePiece;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(70, 70), NO, 0.0f);
    [PCConnect4 drawBluePiece];
    _imageOfBluePiece = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfBluePiece;
}

+ (UIImage*)imageOfRedPiece;
{
    if (_imageOfRedPiece)
        return _imageOfRedPiece;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(70, 70), NO, 0.0f);
    [PCConnect4 drawRedPiece];
    _imageOfRedPiece = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfRedPiece;
}

+ (UIImage*)imageOfCircleTableWithScaleCircle: (CGFloat)scaleCircle;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(640, 282), NO, 0.0f);
    [PCConnect4 drawCircleTableWithScaleCircle: scaleCircle];
    UIImage* imageOfCircleTable = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfCircleTable;
}

+ (UIImage*)imageOfSlotTableWithNumber2: (CGFloat)number2 dx: (CGFloat)dx;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(640, 282), NO, 0.0f);
    [PCConnect4 drawSlotTableWithNumber2: number2 dx: dx];
    UIImage* imageOfSlotTable = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfSlotTable;
}

#pragma mark Customization Infrastructure

- (void)setConnect4BoardTargets: (NSArray*)connect4BoardTargets
{
    _connect4BoardTargets = connect4BoardTargets;

    for (id target in self.connect4BoardTargets)
        [target setImage: PCConnect4.imageOfConnect4Board];
}

- (void)setBluePieceTargets: (NSArray*)bluePieceTargets
{
    _bluePieceTargets = bluePieceTargets;

    for (id target in self.bluePieceTargets)
        [target setImage: PCConnect4.imageOfBluePiece];
}

- (void)setRedPieceTargets: (NSArray*)redPieceTargets
{
    _redPieceTargets = redPieceTargets;

    for (id target in self.redPieceTargets)
        [target setImage: PCConnect4.imageOfRedPiece];
}


@end
