//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 7/24/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Cache

static UIImage* _imageOfConnect4Board = nil;
static UIImage* _imageOfBluePiece = nil;
static UIImage* _imageOfRedPiece = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawConnect4Board;
{
    //// Color Declarations
    UIColor* gameBoardYellow = [UIColor colorWithRed: 0.991 green: 0.982 blue: 0.069 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(477.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 67.27) controlPoint1: CGPointMake(465.42, 35.03) controlPoint2: CGPointMake(465.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 67.27) controlPoint1: CGPointMake(490.03, 79.58) controlPoint2: CGPointMake(509.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 22.73) controlPoint1: CGPointMake(534.58, 54.97) controlPoint2: CGPointMake(534.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 22.73) controlPoint1: CGPointMake(509.97, 10.42) controlPoint2: CGPointMake(490.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 67.27) controlPoint1: CGPointMake(395.42, 35.03) controlPoint2: CGPointMake(395.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 67.27) controlPoint1: CGPointMake(420.03, 79.58) controlPoint2: CGPointMake(439.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 22.73) controlPoint1: CGPointMake(464.58, 54.97) controlPoint2: CGPointMake(464.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 22.73) controlPoint1: CGPointMake(439.97, 10.42) controlPoint2: CGPointMake(420.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 67.27) controlPoint1: CGPointMake(325.42, 35.03) controlPoint2: CGPointMake(325.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 67.27) controlPoint1: CGPointMake(350.03, 79.58) controlPoint2: CGPointMake(369.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 22.73) controlPoint1: CGPointMake(394.58, 54.97) controlPoint2: CGPointMake(394.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 22.73) controlPoint1: CGPointMake(369.97, 10.42) controlPoint2: CGPointMake(350.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 67.27) controlPoint1: CGPointMake(255.42, 35.03) controlPoint2: CGPointMake(255.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 67.27) controlPoint1: CGPointMake(280.03, 79.58) controlPoint2: CGPointMake(299.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 22.73) controlPoint1: CGPointMake(324.58, 54.97) controlPoint2: CGPointMake(324.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 22.73) controlPoint1: CGPointMake(299.97, 10.42) controlPoint2: CGPointMake(280.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 67.27) controlPoint1: CGPointMake(185.42, 35.03) controlPoint2: CGPointMake(185.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 67.27) controlPoint1: CGPointMake(210.03, 79.58) controlPoint2: CGPointMake(229.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 22.73) controlPoint1: CGPointMake(254.58, 54.97) controlPoint2: CGPointMake(254.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 22.73) controlPoint1: CGPointMake(229.97, 10.42) controlPoint2: CGPointMake(210.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 67.27) controlPoint1: CGPointMake(115.42, 35.03) controlPoint2: CGPointMake(115.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 67.27) controlPoint1: CGPointMake(140.03, 79.58) controlPoint2: CGPointMake(159.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 22.73) controlPoint1: CGPointMake(184.58, 54.97) controlPoint2: CGPointMake(184.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 22.73) controlPoint1: CGPointMake(159.97, 10.42) controlPoint2: CGPointMake(140.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 22.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 67.27) controlPoint1: CGPointMake(45.42, 35.03) controlPoint2: CGPointMake(45.42, 54.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 67.27) controlPoint1: CGPointMake(70.03, 79.58) controlPoint2: CGPointMake(89.97, 79.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 22.73) controlPoint1: CGPointMake(114.58, 54.97) controlPoint2: CGPointMake(114.58, 35.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 22.73) controlPoint1: CGPointMake(89.97, 10.42) controlPoint2: CGPointMake(70.03, 10.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 137.27) controlPoint1: CGPointMake(465.42, 105.03) controlPoint2: CGPointMake(465.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 137.27) controlPoint1: CGPointMake(490.03, 149.58) controlPoint2: CGPointMake(509.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 92.73) controlPoint1: CGPointMake(534.58, 124.97) controlPoint2: CGPointMake(534.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 92.73) controlPoint1: CGPointMake(509.97, 80.42) controlPoint2: CGPointMake(490.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 137.27) controlPoint1: CGPointMake(395.42, 105.03) controlPoint2: CGPointMake(395.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 137.27) controlPoint1: CGPointMake(420.03, 149.58) controlPoint2: CGPointMake(439.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 92.73) controlPoint1: CGPointMake(464.58, 124.97) controlPoint2: CGPointMake(464.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 92.73) controlPoint1: CGPointMake(439.97, 80.42) controlPoint2: CGPointMake(420.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 137.27) controlPoint1: CGPointMake(325.42, 105.03) controlPoint2: CGPointMake(325.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 137.27) controlPoint1: CGPointMake(350.03, 149.58) controlPoint2: CGPointMake(369.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 92.73) controlPoint1: CGPointMake(394.58, 124.97) controlPoint2: CGPointMake(394.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 92.73) controlPoint1: CGPointMake(369.97, 80.42) controlPoint2: CGPointMake(350.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 137.27) controlPoint1: CGPointMake(255.42, 105.03) controlPoint2: CGPointMake(255.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 137.27) controlPoint1: CGPointMake(280.03, 149.58) controlPoint2: CGPointMake(299.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 92.73) controlPoint1: CGPointMake(324.58, 124.97) controlPoint2: CGPointMake(324.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 92.73) controlPoint1: CGPointMake(299.97, 80.42) controlPoint2: CGPointMake(280.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 137.27) controlPoint1: CGPointMake(185.42, 105.03) controlPoint2: CGPointMake(185.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 137.27) controlPoint1: CGPointMake(210.03, 149.58) controlPoint2: CGPointMake(229.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 92.73) controlPoint1: CGPointMake(254.58, 124.97) controlPoint2: CGPointMake(254.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 92.73) controlPoint1: CGPointMake(229.97, 80.42) controlPoint2: CGPointMake(210.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 137.27) controlPoint1: CGPointMake(115.42, 105.03) controlPoint2: CGPointMake(115.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 137.27) controlPoint1: CGPointMake(140.03, 149.58) controlPoint2: CGPointMake(159.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 92.73) controlPoint1: CGPointMake(184.58, 124.97) controlPoint2: CGPointMake(184.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 92.73) controlPoint1: CGPointMake(159.97, 80.42) controlPoint2: CGPointMake(140.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 92.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 137.27) controlPoint1: CGPointMake(45.42, 105.03) controlPoint2: CGPointMake(45.42, 124.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 137.27) controlPoint1: CGPointMake(70.03, 149.58) controlPoint2: CGPointMake(89.97, 149.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 92.73) controlPoint1: CGPointMake(114.58, 124.97) controlPoint2: CGPointMake(114.58, 105.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 92.73) controlPoint1: CGPointMake(89.97, 80.42) controlPoint2: CGPointMake(70.03, 80.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 207.27) controlPoint1: CGPointMake(465.42, 175.03) controlPoint2: CGPointMake(465.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 207.27) controlPoint1: CGPointMake(490.03, 219.58) controlPoint2: CGPointMake(509.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 162.73) controlPoint1: CGPointMake(534.58, 194.97) controlPoint2: CGPointMake(534.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 162.73) controlPoint1: CGPointMake(509.97, 150.42) controlPoint2: CGPointMake(490.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 207.27) controlPoint1: CGPointMake(395.42, 175.03) controlPoint2: CGPointMake(395.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 207.27) controlPoint1: CGPointMake(420.03, 219.58) controlPoint2: CGPointMake(439.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 162.73) controlPoint1: CGPointMake(464.58, 194.97) controlPoint2: CGPointMake(464.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 162.73) controlPoint1: CGPointMake(439.97, 150.42) controlPoint2: CGPointMake(420.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 207.27) controlPoint1: CGPointMake(325.42, 175.03) controlPoint2: CGPointMake(325.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 207.27) controlPoint1: CGPointMake(350.03, 219.58) controlPoint2: CGPointMake(369.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 162.73) controlPoint1: CGPointMake(394.58, 194.97) controlPoint2: CGPointMake(394.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 162.73) controlPoint1: CGPointMake(369.97, 150.42) controlPoint2: CGPointMake(350.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 207.27) controlPoint1: CGPointMake(255.42, 175.03) controlPoint2: CGPointMake(255.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 207.27) controlPoint1: CGPointMake(280.03, 219.58) controlPoint2: CGPointMake(299.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 162.73) controlPoint1: CGPointMake(324.58, 194.97) controlPoint2: CGPointMake(324.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 162.73) controlPoint1: CGPointMake(299.97, 150.42) controlPoint2: CGPointMake(280.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 207.27) controlPoint1: CGPointMake(185.42, 175.03) controlPoint2: CGPointMake(185.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 207.27) controlPoint1: CGPointMake(210.03, 219.58) controlPoint2: CGPointMake(229.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 162.73) controlPoint1: CGPointMake(254.58, 194.97) controlPoint2: CGPointMake(254.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 162.73) controlPoint1: CGPointMake(229.97, 150.42) controlPoint2: CGPointMake(210.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 207.27) controlPoint1: CGPointMake(115.42, 175.03) controlPoint2: CGPointMake(115.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 207.27) controlPoint1: CGPointMake(140.03, 219.58) controlPoint2: CGPointMake(159.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 162.73) controlPoint1: CGPointMake(184.58, 194.97) controlPoint2: CGPointMake(184.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 162.73) controlPoint1: CGPointMake(159.97, 150.42) controlPoint2: CGPointMake(140.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 162.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 207.27) controlPoint1: CGPointMake(45.42, 175.03) controlPoint2: CGPointMake(45.42, 194.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 207.27) controlPoint1: CGPointMake(70.03, 219.58) controlPoint2: CGPointMake(89.97, 219.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 162.73) controlPoint1: CGPointMake(114.58, 194.97) controlPoint2: CGPointMake(114.58, 175.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 162.73) controlPoint1: CGPointMake(89.97, 150.42) controlPoint2: CGPointMake(70.03, 150.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(128.23, 232.23)];
    [bezierPath addCurveToPoint: CGPointMake(128.23, 276.77) controlPoint1: CGPointMake(115.92, 244.53) controlPoint2: CGPointMake(115.92, 264.47)];
    [bezierPath addCurveToPoint: CGPointMake(172.77, 276.77) controlPoint1: CGPointMake(140.53, 289.08) controlPoint2: CGPointMake(160.47, 289.08)];
    [bezierPath addCurveToPoint: CGPointMake(172.77, 232.23) controlPoint1: CGPointMake(185.08, 264.47) controlPoint2: CGPointMake(185.08, 244.53)];
    [bezierPath addCurveToPoint: CGPointMake(128.23, 232.23) controlPoint1: CGPointMake(160.47, 219.92) controlPoint2: CGPointMake(140.53, 219.92)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 277.27) controlPoint1: CGPointMake(465.42, 245.03) controlPoint2: CGPointMake(465.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 277.27) controlPoint1: CGPointMake(490.03, 289.58) controlPoint2: CGPointMake(509.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 232.73) controlPoint1: CGPointMake(534.58, 264.97) controlPoint2: CGPointMake(534.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 232.73) controlPoint1: CGPointMake(509.97, 220.42) controlPoint2: CGPointMake(490.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 277.27) controlPoint1: CGPointMake(395.42, 245.03) controlPoint2: CGPointMake(395.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 277.27) controlPoint1: CGPointMake(420.03, 289.58) controlPoint2: CGPointMake(439.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 232.73) controlPoint1: CGPointMake(464.58, 264.97) controlPoint2: CGPointMake(464.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 232.73) controlPoint1: CGPointMake(439.97, 220.42) controlPoint2: CGPointMake(420.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 277.27) controlPoint1: CGPointMake(325.42, 245.03) controlPoint2: CGPointMake(325.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 277.27) controlPoint1: CGPointMake(350.03, 289.58) controlPoint2: CGPointMake(369.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 232.73) controlPoint1: CGPointMake(394.58, 264.97) controlPoint2: CGPointMake(394.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 232.73) controlPoint1: CGPointMake(369.97, 220.42) controlPoint2: CGPointMake(350.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 277.27) controlPoint1: CGPointMake(255.42, 245.03) controlPoint2: CGPointMake(255.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 277.27) controlPoint1: CGPointMake(280.03, 289.58) controlPoint2: CGPointMake(299.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 232.73) controlPoint1: CGPointMake(324.58, 264.97) controlPoint2: CGPointMake(324.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 232.73) controlPoint1: CGPointMake(299.97, 220.42) controlPoint2: CGPointMake(280.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 277.27) controlPoint1: CGPointMake(185.42, 245.03) controlPoint2: CGPointMake(185.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 277.27) controlPoint1: CGPointMake(210.03, 289.58) controlPoint2: CGPointMake(229.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 232.73) controlPoint1: CGPointMake(254.58, 264.97) controlPoint2: CGPointMake(254.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 232.73) controlPoint1: CGPointMake(229.97, 220.42) controlPoint2: CGPointMake(210.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 232.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 277.27) controlPoint1: CGPointMake(45.42, 245.03) controlPoint2: CGPointMake(45.42, 264.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 277.27) controlPoint1: CGPointMake(70.03, 289.58) controlPoint2: CGPointMake(89.97, 289.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 232.73) controlPoint1: CGPointMake(114.58, 264.97) controlPoint2: CGPointMake(114.58, 245.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 232.73) controlPoint1: CGPointMake(89.97, 220.42) controlPoint2: CGPointMake(70.03, 220.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 347.27) controlPoint1: CGPointMake(465.42, 315.03) controlPoint2: CGPointMake(465.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 347.27) controlPoint1: CGPointMake(490.03, 359.58) controlPoint2: CGPointMake(509.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 302.73) controlPoint1: CGPointMake(534.58, 334.97) controlPoint2: CGPointMake(534.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 302.73) controlPoint1: CGPointMake(509.97, 290.42) controlPoint2: CGPointMake(490.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 347.27) controlPoint1: CGPointMake(395.42, 315.03) controlPoint2: CGPointMake(395.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 347.27) controlPoint1: CGPointMake(420.03, 359.58) controlPoint2: CGPointMake(439.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 302.73) controlPoint1: CGPointMake(464.58, 334.97) controlPoint2: CGPointMake(464.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 302.73) controlPoint1: CGPointMake(439.97, 290.42) controlPoint2: CGPointMake(420.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 347.27) controlPoint1: CGPointMake(325.42, 315.03) controlPoint2: CGPointMake(325.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 347.27) controlPoint1: CGPointMake(350.03, 359.58) controlPoint2: CGPointMake(369.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 302.73) controlPoint1: CGPointMake(394.58, 334.97) controlPoint2: CGPointMake(394.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 302.73) controlPoint1: CGPointMake(369.97, 290.42) controlPoint2: CGPointMake(350.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 347.27) controlPoint1: CGPointMake(255.42, 315.03) controlPoint2: CGPointMake(255.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 347.27) controlPoint1: CGPointMake(280.03, 359.58) controlPoint2: CGPointMake(299.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 302.73) controlPoint1: CGPointMake(324.58, 334.97) controlPoint2: CGPointMake(324.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 302.73) controlPoint1: CGPointMake(299.97, 290.42) controlPoint2: CGPointMake(280.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 347.27) controlPoint1: CGPointMake(185.42, 315.03) controlPoint2: CGPointMake(185.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 347.27) controlPoint1: CGPointMake(210.03, 359.58) controlPoint2: CGPointMake(229.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 302.73) controlPoint1: CGPointMake(254.58, 334.97) controlPoint2: CGPointMake(254.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 302.73) controlPoint1: CGPointMake(229.97, 290.42) controlPoint2: CGPointMake(210.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 347.27) controlPoint1: CGPointMake(115.42, 315.03) controlPoint2: CGPointMake(115.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 347.27) controlPoint1: CGPointMake(140.03, 359.58) controlPoint2: CGPointMake(159.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 302.73) controlPoint1: CGPointMake(184.58, 334.97) controlPoint2: CGPointMake(184.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 302.73) controlPoint1: CGPointMake(159.97, 290.42) controlPoint2: CGPointMake(140.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 302.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 347.27) controlPoint1: CGPointMake(45.42, 315.03) controlPoint2: CGPointMake(45.42, 334.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 347.27) controlPoint1: CGPointMake(70.03, 359.58) controlPoint2: CGPointMake(89.97, 359.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 302.73) controlPoint1: CGPointMake(114.58, 334.97) controlPoint2: CGPointMake(114.58, 315.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 302.73) controlPoint1: CGPointMake(89.97, 290.42) controlPoint2: CGPointMake(70.03, 290.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(477.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 417.27) controlPoint1: CGPointMake(465.42, 385.03) controlPoint2: CGPointMake(465.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 417.27) controlPoint1: CGPointMake(490.03, 429.58) controlPoint2: CGPointMake(509.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(522.27, 372.73) controlPoint1: CGPointMake(534.58, 404.97) controlPoint2: CGPointMake(534.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(477.73, 372.73) controlPoint1: CGPointMake(509.97, 360.42) controlPoint2: CGPointMake(490.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(407.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 417.27) controlPoint1: CGPointMake(395.42, 385.03) controlPoint2: CGPointMake(395.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 417.27) controlPoint1: CGPointMake(420.03, 429.58) controlPoint2: CGPointMake(439.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(452.27, 372.73) controlPoint1: CGPointMake(464.58, 404.97) controlPoint2: CGPointMake(464.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(407.73, 372.73) controlPoint1: CGPointMake(439.97, 360.42) controlPoint2: CGPointMake(420.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(337.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 417.27) controlPoint1: CGPointMake(325.42, 385.03) controlPoint2: CGPointMake(325.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 417.27) controlPoint1: CGPointMake(350.03, 429.58) controlPoint2: CGPointMake(369.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(382.27, 372.73) controlPoint1: CGPointMake(394.58, 404.97) controlPoint2: CGPointMake(394.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(337.73, 372.73) controlPoint1: CGPointMake(369.97, 360.42) controlPoint2: CGPointMake(350.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(267.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 417.27) controlPoint1: CGPointMake(255.42, 385.03) controlPoint2: CGPointMake(255.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 417.27) controlPoint1: CGPointMake(280.03, 429.58) controlPoint2: CGPointMake(299.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(312.27, 372.73) controlPoint1: CGPointMake(324.58, 404.97) controlPoint2: CGPointMake(324.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(267.73, 372.73) controlPoint1: CGPointMake(299.97, 360.42) controlPoint2: CGPointMake(280.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(197.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 417.27) controlPoint1: CGPointMake(185.42, 385.03) controlPoint2: CGPointMake(185.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 417.27) controlPoint1: CGPointMake(210.03, 429.58) controlPoint2: CGPointMake(229.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(242.27, 372.73) controlPoint1: CGPointMake(254.58, 404.97) controlPoint2: CGPointMake(254.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(197.73, 372.73) controlPoint1: CGPointMake(229.97, 360.42) controlPoint2: CGPointMake(210.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(127.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 417.27) controlPoint1: CGPointMake(115.42, 385.03) controlPoint2: CGPointMake(115.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 417.27) controlPoint1: CGPointMake(140.03, 429.58) controlPoint2: CGPointMake(159.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(172.27, 372.73) controlPoint1: CGPointMake(184.58, 404.97) controlPoint2: CGPointMake(184.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(127.73, 372.73) controlPoint1: CGPointMake(159.97, 360.42) controlPoint2: CGPointMake(140.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(57.73, 372.73)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 417.27) controlPoint1: CGPointMake(45.42, 385.03) controlPoint2: CGPointMake(45.42, 404.97)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 417.27) controlPoint1: CGPointMake(70.03, 429.58) controlPoint2: CGPointMake(89.97, 429.58)];
    [bezierPath addCurveToPoint: CGPointMake(102.27, 372.73) controlPoint1: CGPointMake(114.58, 404.97) controlPoint2: CGPointMake(114.58, 385.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.73, 372.73) controlPoint1: CGPointMake(89.97, 360.42) controlPoint2: CGPointMake(70.03, 360.42)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(545, 0)];
    [bezierPath addCurveToPoint: CGPointMake(545, 440) controlPoint1: CGPointMake(545, 0) controlPoint2: CGPointMake(545, 440)];
    [bezierPath addLineToPoint: CGPointMake(35, 440)];
    [bezierPath addLineToPoint: CGPointMake(35, 0)];
    [bezierPath addLineToPoint: CGPointMake(545, 0)];
    [bezierPath addLineToPoint: CGPointMake(545, 0)];
    [bezierPath closePath];
    [gameBoardYellow setFill];
    [bezierPath fill];


    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(545, 0, 20, 507)];
    [gameBoardYellow setFill];
    [rectanglePath fill];


    //// Rectangle 3 Drawing
    UIBezierPath* rectangle3Path = [UIBezierPath bezierPathWithRect: CGRectMake(15, 0, 20, 507)];
    [gameBoardYellow setFill];
    [rectangle3Path fill];


    //// Rectangle 4 Drawing
    UIBezierPath* rectangle4Path = [UIBezierPath bezierPathWithRect: CGRectMake(530, 487, 50, 20)];
    [gameBoardYellow setFill];
    [rectangle4Path fill];


    //// Rectangle 5 Drawing
    UIBezierPath* rectangle5Path = [UIBezierPath bezierPathWithRect: CGRectMake(0, 487, 50, 20)];
    [gameBoardYellow setFill];
    [rectangle5Path fill];
}

+ (void)drawBluePiece;
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* pieceBlue = [UIColor colorWithRed: 0.135 green: 0.566 blue: 0.854 alpha: 1];
    CGFloat pieceBlueRGBA[4];
    [pieceBlue getRed: &pieceBlueRGBA[0] green: &pieceBlueRGBA[1] blue: &pieceBlueRGBA[2] alpha: &pieceBlueRGBA[3]];

    UIColor* shadowPieceBlue = [UIColor colorWithRed: (pieceBlueRGBA[0] * 0.7) green: (pieceBlueRGBA[1] * 0.7) blue: (pieceBlueRGBA[2] * 0.7) alpha: (pieceBlueRGBA[3] * 0.7 + 0.3)];

    //// Gradient Declarations
    CGFloat blueGamePieceLocations[] = {0, 0.41, 1};
    CGGradientRef blueGamePiece = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)pieceBlue.CGColor, (id)[UIColor colorWithRed: 0.115 green: 0.481 blue: 0.726 alpha: 1].CGColor, (id)shadowPieceBlue.CGColor], blueGamePieceLocations);

    //// Oval Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 35, 35);

    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-35, -35, 70, 70)];
    [shadowPieceBlue setFill];
    [ovalPath fill];

    CGContextRestoreGState(context);


    //// Oval 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 35, 35);

    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-32.5, -32.5, 65, 65)];
    CGContextSaveGState(context);
    [oval2Path addClip];
    CGContextDrawRadialGradient(context, blueGamePiece,
        CGPointMake(-1.59, -2.7), 34.14,
        CGPointMake(0, 0), 23.94,
        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
    CGContextRestoreGState(context);

    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(blueGamePiece);
    CGColorSpaceRelease(colorSpace);
}

+ (void)drawRedPiece;
{
    //// General Declarations
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* pieceRed = [UIColor colorWithRed: 0.968 green: 0.272 blue: 0.108 alpha: 1];
    CGFloat pieceRedRGBA[4];
    [pieceRed getRed: &pieceRedRGBA[0] green: &pieceRedRGBA[1] blue: &pieceRedRGBA[2] alpha: &pieceRedRGBA[3]];

    UIColor* shadowPieceRed = [UIColor colorWithRed: (pieceRedRGBA[0] * 0.8) green: (pieceRedRGBA[1] * 0.8) blue: (pieceRedRGBA[2] * 0.8) alpha: (pieceRedRGBA[3] * 0.8 + 0.2)];

    //// Gradient Declarations
    CGFloat redGamePieceLocations[] = {0, 1};
    CGGradientRef redGamePiece = CGGradientCreateWithColors(colorSpace, (__bridge CFArrayRef)@[(id)pieceRed.CGColor, (id)shadowPieceRed.CGColor], redGamePieceLocations);

    //// Oval Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 35, 35);

    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-35, -35, 70, 70)];
    [shadowPieceRed setFill];
    [ovalPath fill];

    CGContextRestoreGState(context);


    //// Oval 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 35, 35);

    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(-32.5, -32.5, 65, 65)];
    CGContextSaveGState(context);
    [oval2Path addClip];
    CGContextDrawRadialGradient(context, redGamePiece,
        CGPointMake(-1.59, -2.7), 34.14,
        CGPointMake(0, 0), 23.94,
        kCGGradientDrawsBeforeStartLocation | kCGGradientDrawsAfterEndLocation);
    CGContextRestoreGState(context);

    CGContextRestoreGState(context);


    //// Cleanup
    CGGradientRelease(redGamePiece);
    CGColorSpaceRelease(colorSpace);
}

#pragma mark Generated Images

+ (UIImage*)imageOfConnect4Board;
{
    if (_imageOfConnect4Board)
        return _imageOfConnect4Board;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(580, 508), NO, 0.0f);
    [StyleKitName drawConnect4Board];
    _imageOfConnect4Board = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfConnect4Board;
}

+ (UIImage*)imageOfBluePiece;
{
    if (_imageOfBluePiece)
        return _imageOfBluePiece;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(70, 70), NO, 0.0f);
    [StyleKitName drawBluePiece];
    _imageOfBluePiece = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfBluePiece;
}

+ (UIImage*)imageOfRedPiece;
{
    if (_imageOfRedPiece)
        return _imageOfRedPiece;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(70, 70), NO, 0.0f);
    [StyleKitName drawRedPiece];
    _imageOfRedPiece = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfRedPiece;
}

#pragma mark Customization Infrastructure

- (void)setConnect4BoardTargets: (NSArray*)connect4BoardTargets
{
    _connect4BoardTargets = connect4BoardTargets;

    for (id target in self.connect4BoardTargets)
        [target setImage: StyleKitName.imageOfConnect4Board];
}

- (void)setBluePieceTargets: (NSArray*)bluePieceTargets
{
    _bluePieceTargets = bluePieceTargets;

    for (id target in self.bluePieceTargets)
        [target setImage: StyleKitName.imageOfBluePiece];
}

- (void)setRedPieceTargets: (NSArray*)redPieceTargets
{
    _redPieceTargets = redPieceTargets;

    for (id target in self.redPieceTargets)
        [target setImage: StyleKitName.imageOfRedPiece];
}


@end
