//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 7/24/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* connect4BoardTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* bluePieceTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* redPieceTargets;

// Drawing Methods
+ (void)drawConnect4Board;
+ (void)drawBluePiece;
+ (void)drawRedPiece;

// Generated Images
+ (UIImage*)imageOfConnect4Board;
+ (UIImage*)imageOfBluePiece;
+ (UIImage*)imageOfRedPiece;

@end
